(() => {
  const qs=id=>document.getElementById(id); const POLL_MS=20000; let pin='',state=null,pollTimer=null,busy=false;
  function toast(msg){const t=qs('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
  function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function setBusy(v){busy=v;document.body.classList.toggle('loading',v)}
  async function api(url,opts={}){const r=await fetch(url,{cache:'no-store',headers:{'Content-Type':'application/json','X-Admin-Pin':pin,...(opts.headers||{})},...opts});let d={};try{d=await r.json()}catch(_){}if(!r.ok)throw new Error(d.detail||`Erro HTTP ${r.status}`);return d}
  async function login(){pin=(qs('pin').value||'').trim();if(!pin)return toast('Digite o PIN administrativo.');setBusy(true);try{state=await api('/api/admin/state');qs('adminArea').hidden=false;render();qs('connText').textContent='Admin conectado';qs('connDot').className='dot ok';if(!pollTimer)pollTimer=setInterval(()=>refresh(true),POLL_MS)}catch(e){toast(e.message);qs('adminArea').hidden=true;qs('connText').textContent='Acesso negado';qs('connDot').className='dot off'}finally{setBusy(false)}}
  async function refresh(silent=false){if(!pin)return;if(!silent)setBusy(true);try{state=await api('/api/admin/state');render()}catch(e){if(!silent)toast(e.message)}finally{if(!silent)setBusy(false)}}
  function render(){if(!state)return;const e=state.event,q=state.queue||[],c=state.choices||[],units=state.units||[];qs('eventStatus').textContent=e.is_open?'Escolhas abertas':'Escolhas fechadas';qs('eventDot').className='dot '+(e.is_open?'ok':'off');qs('queueCount').textContent=q.length;qs('choiceCount').textContent=c.length;qs('currentPos').textContent=e.current_position||'—';qs('remainingCount').textContent=units.reduce((a,u)=>a+Number(u.remaining||0),0);const cur=q.find(x=>Number(x.position)===Number(e.current_position));qs('currentNotice').className='notice '+(e.is_open?'turn':'closed');qs('currentNotice').innerHTML=cur?`<strong>Em pista: ${esc(cur.name)}</strong><br>${e.is_open?'A escolha está liberada.':'A sessão está fechada.'}`:'<strong>Fila concluída ou ainda não cadastrada.</strong>';qs('openBtn').disabled=e.is_open||busy;qs('closeBtn').disabled=!e.is_open||busy;qs('undoBtn').disabled=!c.length||busy;qs('resetBtn').disabled=!c.length||busy;if(document.activeElement!==qs('names'))qs('names').value=q.map(x=>x.name).join('\n');const chosen=new Set(c.map(x=>Number(x.position)));qs('queueBody').innerHTML=q.map(x=>`<tr><td>${x.position}º</td><td>${esc(x.name)}</td><td>${chosen.has(Number(x.position))?'Escolheu':Number(x.position)===Number(e.current_position)?'Em pista':'Aguardando'}</td></tr>`).join('')||'<tr><td colspan="3">Nenhuma fila cadastrada.</td></tr>';qs('resultsBody').innerHTML=c.map(x=>`<tr><td>${x.position}º</td><td>${esc(x.name)}</td><td>${esc(x.region)}</td><td>${esc(x.unit)}</td><td>${esc(x.city)}</td><td>${new Date(x.created_at).toLocaleString('pt-BR')}</td></tr>`).join('')||'<tr><td colspan="6">Nenhuma escolha registrada.</td></tr>'}
  async function replaceQueue(){const names=qs('names').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!names.length)return toast('A lista está vazia.');if(!confirm(`Salvar ${names.length} nomes como nova fila? Isso apaga as escolhas existentes.`))return;setBusy(true);try{state=await api('/api/admin/queue',{method:'POST',body:JSON.stringify({names})});render();toast('Nova fila salva.')}catch(e){toast(e.message)}finally{setBusy(false)}}
  async function setOpen(open){setBusy(true);try{state=await api('/api/admin/open',{method:'POST',body:JSON.stringify({open})});render();toast(open?'Escolhas abertas.':'Escolhas fechadas.')}catch(e){toast(e.message)}finally{setBusy(false)}}
  async function undo(){if(!confirm('Desfazer a última escolha e devolver a vez ao último militar?'))return;setBusy(true);try{state=await api('/api/admin/undo',{method:'POST'});render();toast('Última escolha desfeita.')}catch(e){toast(e.message)}finally{setBusy(false)}}
  async function reset(){if(!confirm('Zerar todas as escolhas? A fila será mantida.'))return;setBusy(true);try{state=await api('/api/admin/reset',{method:'POST'});render();toast('Escolhas zeradas.')}catch(e){toast(e.message)}finally{setBusy(false)}}
  function csvDownload(filename,rows){const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  function downloadResults(){const rows=[['Ordem','Nome','Comando','OM','Cidade','Data/Hora']];(state.choices||[]).forEach(c=>rows.push([c.position,c.name,c.region,c.unit,c.city,new Date(c.created_at).toLocaleString('pt-BR')]));csvDownload('resultado_escolha_om.csv',rows)}
  qs('loginBtn').onclick=login;qs('pin').addEventListener('keydown',e=>{if(e.key==='Enter')login()});qs('replaceBtn').onclick=replaceQueue;qs('openBtn').onclick=()=>setOpen(true);qs('closeBtn').onclick=()=>setOpen(false);qs('undoBtn').onclick=undo;qs('resetBtn').onclick=reset;qs('downloadResults').onclick=downloadResults;
})();
